In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/DontGetKicked/example_entry.csv
/kaggle/input/DontGetKicked/training.zip
/kaggle/input/DontGetKicked/Carvana_Data_Dictionary.txt
/kaggle/input/DontGetKicked/test.zip
/kaggle/input/DontGetKicked/training.csv
/kaggle/input/DontGetKicked/test.csv

In [2]:
pd.options.display.max_columns = 999

In [3]:
train = pd.read_csv('/kaggle/input/DontGetKicked/training.csv')
test = pd.read_csv('/kaggle/input/DontGetKicked/test.csv')

In [4]:
display(train, test)

,RefId,IsBadBuy,PurchDate,Auction,VehYear,VehicleAge,Make,Model,Trim,SubModel,Color,Transmission,WheelTypeID,WheelType,VehOdo,Nationality,Size,TopThreeAmericanName,MMRAcquisitionAuctionAveragePrice,MMRAcquisitionAuctionCleanPrice,MMRAcquisitionRetailAveragePrice,MMRAcquisitonRetailCleanPrice,MMRCurrentAuctionAveragePrice,MMRCurrentAuctionCleanPrice,MMRCurrentRetailAveragePrice,MMRCurrentRetailCleanPrice,PRIMEUNIT,AUCGUART,BYRNO,VNZIP1,VNST,VehBCost,IsOnlineSale,WarrantyCost
0,1,0,12/7/2009,ADESA,2006,3,MAZDA,MAZDA3,i,4D SEDAN I,RED,AUTO,1.0,Alloy,89046,OTHER ASIAN,MEDIUM,OTHER,8155.0,9829.0,11636.0,13600.0,7451.0,8552.0,11597.0,12409.0,NaN,NaN,21973,33619,FL,7100.0,0,1113
1,2,0,12/7/2009,ADESA,2004,5,DODGE,1500 RAM PICKUP 2WD,ST,QUAD CAB 4.7L SLT,WHITE,AUTO,1.0,Alloy,93593,AMERICAN,LARGE TRUCK,CHRYSLER,6854.0,8383.0,10897.0,12572.0,7456.0,9222.0,11374.0,12791.0,NaN,NaN,19638,33619,FL,7600.0,0,1053
2,3,0,12/7/2009,ADESA,2005,4,DODGE,STRATUS V6,SXT,4D SEDAN SXT FFV,MAROON,AUTO,2.0,Covers,73807,AMERICAN,MEDIUM,CHRYSLER,3202.0,4760.0,6943.0,8457.0,4035.0,5557.0,7146.0,8702.0,NaN,NaN,19638,33619,FL,4900.0,0,1389
3,4,0,12/7/2009,ADESA,2004,5,DODGE,NEON,SXT,4D SEDAN,SILVER,AUTO,1.0,Alloy,65617,AMERICAN,COMPACT,CHRYSLER,1893.0,2675.0,4658.0,5690.0,1844.0,2646.0,4375.0,5518.0,NaN,NaN,19638,33619,FL,4100.0,0,630
4,5,0,12/7/2009,ADESA,2005,4,FORD,FOCUS,ZX3,2D COUPE ZX3,SILVER,MANUAL,2.0,Covers,69367,AMERICAN,COMPACT,FORD,3913.0,5054.0,7723.0,8707.0,3247.0,4384.0,6739.0,7911.0,NaN,NaN,19638,33619,FL,4000.0,0,1020
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
72978,73010,1,12/2/2009,ADESA,2001,8,MERCURY,SABLE,GS,4D SEDAN GS,BLACK,AUTO,1.0,Alloy,45234,AMERICAN,MEDIUM,FORD,1996.0,2993.0,2656.0,3732.0,2190.0,3055.0,4836.0,5937.0,NaN,NaN,18111,30212,GA,4200.0,0,993
72979,73011,0,12/2/2009,ADESA,2007,2,CHEVROLET,MALIBU 4C,LS,4D SEDAN LS,SILVER,AUTO,NaN,NaN,71759,AMERICAN,MEDIUM,GM,6418.0,7325.0,7431.0,8411.0,6785.0,8132.0,10151.0,11652.0,NaN,NaN,18881,30212,GA,6200.0,0,1038
72980,73012,0,12/2/2009,ADESA,2005,4,JEEP,GRAND CHEROKEE 2WD V,Lar,4D WAGON LAREDO,SILVER,AUTO,1.0,Alloy,88500,AMERICAN,MEDIUM SUV,CHRYSLER,8545.0,9959.0,9729.0,11256.0,8375.0,9802.0,11831.0,14402.0,NaN,NaN,18111,30212,GA,8200.0,0,1893
72981,73013,0,12/2/2009,ADESA,2006,3,CHEVROLET,IMPALA,LS,4D SEDAN LS,WHITE,AUTO,1.0,Alloy,79554,AMERICAN,LARGE,GM,6420.0,7604.0,7434.0,8712.0,6590.0,7684.0,10099.0,11228.0,NaN,NaN,18881,30212,GA,7000.0,0,1974
72982,73014,0,12/2/2009,ADESA,2006,3,MAZDA,MAZDA6,s,4D SEDAN S,SILVER,AUTO,1.0,Alloy,66855,OTHER ASIAN,MEDIUM,OTHER,7535.0,8771.0,8638.0,9973.0,7730.0,9102.0,11954.0,13246.0,NaN,NaN,18111,30212,GA,8000.0,0,1313

,RefId,PurchDate,Auction,VehYear,VehicleAge,Make,Model,Trim,SubModel,Color,Transmission,WheelTypeID,WheelType,VehOdo,Nationality,Size,TopThreeAmericanName,MMRAcquisitionAuctionAveragePrice,MMRAcquisitionAuctionCleanPrice,MMRAcquisitionRetailAveragePrice,MMRAcquisitonRetailCleanPrice,MMRCurrentAuctionAveragePrice,MMRCurrentAuctionCleanPrice,MMRCurrentRetailAveragePrice,MMRCurrentRetailCleanPrice,PRIMEUNIT,AUCGUART,BYRNO,VNZIP1,VNST,VehBCost,IsOnlineSale,WarrantyCost
0,73015,12/2/2009,ADESA,2005,4,PONTIAC,GRAND PRIX,Bas,4D SEDAN,SILVER,AUTO,1.0,Alloy,85377,AMERICAN,LARGE,GM,5032.0,6386.0,5935.0,7397.0,4905.0,6181.0,8557.0,9752.0,NaN,NaN,18881,30212,GA,6500.0,0,2152
1,73016,12/2/2009,ADESA,2005,4,CHEVROLET,MALIBU V6,LS,4D SEDAN LS,SILVER,AUTO,1.0,Alloy,61873,AMERICAN,MEDIUM,GM,4502.0,5685.0,5362.0,6640.0,4645.0,5710.0,7562.0,9296.0,NaN,NaN,18111,30212,GA,6300.0,0,1118
2,73017,12/2/2009,ADESA,2006,3,DODGE,DURANGO 2WD V8,Adv,4D SUV 4.7L ADVENTURER,SILVER,AUTO,1.0,Alloy,69283,AMERICAN,MEDIUM SUV,CHRYSLER,10244.0,13041.0,11564.0,14584.0,10883.0,12166.0,15340.0,16512.0,NaN,NaN,18111,30212,GA,9700.0,0,1215
3,73018,12/2/2009,ADESA,2002,7,SATURN,L SERIES,L20,4D SEDAN L200,GOLD,AUTO,1.0,Alloy,87889,AMERICAN,MEDIUM,GM,2558.0,3542.0,3263.0,4325.0,2928.0,3607.0,5725.0,6398.0,NaN,NaN,18881,30212,GA,4150.0,0,1933
4,73019,12/2/2009,ADESA,2007,2,HYUNDAI,ACCENT,GS,2D COUPE GS,BLUE,AUTO,NaN,NaN,73432,OTHER ASIAN,COMPACT,OTHER,5013.0,6343.0,5914.0,7350.0,5013.0,6343.0,5914.0,7350.0,NaN,NaN,18111,30212,GA,4100.0,0,920
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48702,121742,11/17/2010,MANHEIM,2005,5,FORD,FIVE HUNDRED,SEL,4D SEDAN SEL,BLACK,AUTO,1.0,Alloy,88645,AMERICAN,LARGE,FORD,5358.0,6836.0,8987.0,10905.0,5761.0,6965.0,9764.0,11395.0,NaN,NaN,20928,33411,FL,7955.0,0,1633
48703,121743,11/17/2010,MANHEIM,2007,3,TOYOTA,COROLLA,CE,4D SEDAN CE,GREEN,AUTO,2.0,Covers,81862,TOP LINE ASIAN,COMPACT,OTHER,6849.0,7992.0,10999.0,12021.0,6856.0,8183.0,10283.0,11565.0,NaN,NaN,20928,33411,FL,7035.0,0,594
48704,121744,11/17/2010,MANHEIM,2006,4,KIA,SPECTRA,EX,4D SEDAN EX,BLACK,AUTO,2.0,Covers,82451,OTHER ASIAN,MEDIUM,OTHER,4662.0,5655.0,7972.0,9670.0,4833.0,5856.0,7871.0,9490.0,NO,GREEN,20928,33411,FL,6335.0,0,594
48705,121745,11/17/2010,MANHEIM,2005,5,MAZDA,MAZDA3,s,4D SEDAN GT,SILVER,AUTO,1.0,Alloy,75760,OTHER ASIAN,MEDIUM,OTHER,5953.0,8166.0,9137.0,11949.0,5092.0,6853.0,8576.0,9937.0,NO,GREEN,20928,33411,FL,8055.0,0,1038
48706,121746,11/17/2010,MANHEIM,2003,7,BUICK,RENDEZVOUS AWD,CX,4D SUV CX,GOLD,AUTO,2.0,Covers,82174,AMERICAN,MEDIUM SUV,GM,3269.0,4435.0,6893.0,8221.0,4526.0,5761.0,8266.0,9388.0,NO,GREEN,20928,33411,FL,7755.0,0,5392

In [5]:
train['IsBadBuy'].value_counts()

0    64007
1     8976
Name: IsBadBuy, dtype: int64

In [6]:
all_data = pd.concat([train, test])
#Categorical 변수의 Labeling에서 오류 생기는 걸 방지하는 효과도 있음

In [7]:
all_data2 = all_data.drop(columns=['IsBadBuy','RefId','PurchDate'])
#지워지는 이유: 모델이 실수할 수도 있으니까 그 가능성을 없애주기 위해서

In [8]:
all_data2['Auction'].unique()

array(['ADESA', 'OTHER', 'MANHEIM'], dtype=object)

In [9]:
all_data2['Make'].nunique() #Unique 개수
all_data2['Make'].value_counts() #각 변수의 갯수 
all_data2['Make'].unique() #Unique 값들

array(['MAZDA', 'DODGE', 'FORD', 'MITSUBISHI', 'KIA', 'GMC', 'NISSAN',
       'CHEVROLET', 'SATURN', 'CHRYSLER', 'MERCURY', 'HYUNDAI', 'TOYOTA',
       'PONTIAC', 'SUZUKI', 'JEEP', 'HONDA', 'OLDSMOBILE', 'BUICK',
       'SCION', 'VOLKSWAGEN', 'ISUZU', 'LINCOLN', 'MINI', 'SUBARU',
       'CADILLAC', 'VOLVO', 'INFINITI', 'PLYMOUTH', 'LEXUS', 'ACURA',
       'TOYOTA SCION', 'HUMMER'], dtype=object)

## 자동으로 Categorical 변수 처리하기 -> Label Encoder

In [10]:
from sklearn.preprocessing import LabelEncoder

In [11]:
le = LabelEncoder() #library는 ()필요, 여기선 옵션 안 넣어줌 
all_data2['Make'] = le.fit_transform(all_data2['Make'])  #le라는 library안에 있는 fit_transform이라는 함수를 사용해서 labeling한 것

In [12]:
le.classes_

array(['ACURA', 'BUICK', 'CADILLAC', 'CHEVROLET', 'CHRYSLER', 'DODGE',
       'FORD', 'GMC', 'HONDA', 'HUMMER', 'HYUNDAI', 'INFINITI', 'ISUZU',
       'JEEP', 'KIA', 'LEXUS', 'LINCOLN', 'MAZDA', 'MERCURY', 'MINI',
       'MITSUBISHI', 'NISSAN', 'OLDSMOBILE', 'PLYMOUTH', 'PONTIAC',
       'SATURN', 'SCION', 'SUBARU', 'SUZUKI', 'TOYOTA', 'TOYOTA SCION',
       'VOLKSWAGEN', 'VOLVO'], dtype=object)

In [13]:
columns = all_data2.columns
c = columns[all_data2.dtypes == object]

In [14]:
c

Index(['Auction', 'Model', 'Trim', 'SubModel', 'Color', 'Transmission',
       'WheelType', 'Nationality', 'Size', 'TopThreeAmericanName', 'PRIMEUNIT',
       'AUCGUART', 'VNST'],
      dtype='object')

In [15]:
for i in c:
    all_data2[i] = le.fit_transform(list(all_data2[i])) #NaN이라는 값이 리스트에 들어가면 NaN이라는 문자로 바뀜

In [16]:
all_data2

,Auction,VehYear,VehicleAge,Make,Model,Trim,SubModel,Color,Transmission,WheelTypeID,WheelType,VehOdo,Nationality,Size,TopThreeAmericanName,MMRAcquisitionAuctionAveragePrice,MMRAcquisitionAuctionCleanPrice,MMRAcquisitionRetailAveragePrice,MMRAcquisitonRetailCleanPrice,MMRCurrentAuctionAveragePrice,MMRCurrentAuctionCleanPrice,MMRCurrentRetailAveragePrice,MMRCurrentRetailCleanPrice,PRIMEUNIT,AUCGUART,BYRNO,VNZIP1,VNST,VehBCost,IsOnlineSale,WarrantyCost
0,0,2006,3,17,620,135,236,13,0,1.0,0,89046,2,5,3,8155.0,9829.0,11636.0,13600.0,7451.0,8552.0,11597.0,12409.0,2,2,21973,33619,5,7100.0,0,1113
1,0,2004,5,5,0,94,826,15,0,1.0,0,93593,0,4,0,6854.0,8383.0,10897.0,12572.0,7456.0,9222.0,11374.0,12791.0,2,2,19638,33619,5,7600.0,0,1053
2,0,2005,4,5,938,99,311,7,0,2.0,1,73807,0,5,0,3202.0,4760.0,6943.0,8457.0,4035.0,5557.0,7146.0,8702.0,2,2,19638,33619,5,4900.0,0,1389
3,0,2004,5,5,700,99,165,14,0,1.0,0,65617,0,0,0,1893.0,2675.0,4658.0,5690.0,1844.0,2646.0,4375.0,5518.0,2,2,19638,33619,5,4100.0,0,630
4,0,2005,4,6,389,129,55,14,1,2.0,1,69367,0,0,1,3913.0,5054.0,7723.0,8707.0,3247.0,4384.0,6739.0,7911.0,2,2,19638,33619,5,4000.0,0,1020
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48702,1,2005,5,6,386,85,292,1,0,1.0,0,88645,0,2,1,5358.0,6836.0,8987.0,10905.0,5761.0,6965.0,9764.0,11395.0,2,2,20928,33411,5,7955.0,0,1633
48703,1,2007,3,29,241,9,198,5,0,2.0,1,81862,3,0,3,6849.0,7992.0,10999.0,12021.0,6856.0,8183.0,10283.0,11565.0,2,2,20928,33411,5,7035.0,0,594
48704,1,2006,4,14,912,23,210,1,0,2.0,1,82451,2,5,3,4662.0,5655.0,7972.0,9670.0,4833.0,5856.0,7871.0,9490.0,0,0,20928,33411,5,6335.0,0,594
48705,1,2005,5,17,620,137,223,14,0,1.0,0,75760,2,5,3,5953.0,8166.0,9137.0,11949.0,5092.0,6853.0,8576.0,9937.0,0,0,20928,33411,5,8055.0,0,1038
48706,1,2003,7,1,799,10,479,4,0,2.0,1,82174,0,6,2,3269.0,4435.0,6893.0,8221.0,4526.0,5761.0,8266.0,9388.0,0,0,20928,33411,5,7755.0,0,5392

In [17]:
#숫자형 데이터의 결측치 처리
all_data2 = all_data2.fillna(-1)
#-1을 넣는 이유? 
#-> 결측치 자체의 느낌 자체를 학습할 수 있도록 하기 위해서 (평균을 넣으면 결측치라는 특성을 반영하지 못하게 됨)-> 실제 test 셋에서도 결측치를 잘 반영해서 예측하게 됨 
#-> 선형 모델을 사용할 때는(Not 트리모델) 숫자의 특성을 (관계성) 가져오기 때문에 -1, 999 이런 값을 넣으면 모델 자체에 왜곡 일어날 수 있음

In [18]:
train2 = all_data2[:len(train)]
test2 = all_data2[len(train):]

In [19]:
#random Foreast는 시간 bar 못 봄

In [20]:
%%time
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(n_jobs=-1, random_state=42)
rf.fit(train2,train['IsBadBuy'])
result = rf.predict_proba(test2)

CPU times: user 39.4 s, sys: 185 ms, total: 39.5 s
Wall time: 10.6 s

In [21]:
result

array([[0.95, 0.05],
       [0.95, 0.05],
       [0.99, 0.01],
       ...,
       [0.95, 0.05],
       [0.83, 0.17],
       [0.9 , 0.1 ]])

In [22]:
sub = pd.read_csv('/kaggle/input/DontGetKicked/example_entry.csv')

In [23]:
sub

        RefId  IsBadBuy
0       73015         0
1       73016         0
2       73017         0
3       73018         0
4       73019         0
...       ...       ...
48702  121742         0
48703  121743         0
48704  121744         0
48705  121745         0
48706  121746         0

[48707 rows x 2 columns]

In [24]:
sub['IsBadBuy'] = result[:,1]

In [25]:
sub.to_csv('submission.csv',index=None)